name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.io
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/frontend
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/backend

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push the backend Docker image
    - name: Build and Push Backend
      working-directory: ./backend
      run: |
        docker buildx build \
          --build-arg MONGO_DB=${{ secrets.MONGO_DB }} \
          --build-arg JWT=${{ secrets.JWT }} \
          -t $BACKEND_IMAGE:latest .
        docker push $BACKEND_IMAGE:latest 

    # Step 4: Build and push the frontend Docker image
    - name: Build and Push Frontend
      working-directory: ./frontend
      run: |
        docker buildx build \
          --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
          --build-arg REACT_APP_CLOUDINARY_CLOUD_NAME=${{ secrets.REACT_APP_CLOUDINARY_CLOUD_NAME }} \
          --build-arg REACT_APP_CLOUDINARY_UPLOAD_PRESET=${{ secrets.REACT_APP_CLOUDINARY_UPLOAD_PRESET }} \
          -t $FRONTEND_IMAGE:latest .
        docker push $FRONTEND_IMAGE:latest 